src/Entity/Client.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\ClientRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\ManyToOne;
use Doctrine\ORM\Mapping\OneToMany;
use Doctrine\ORM\Mapping\OneToOne;
use Doctrine\ORM\Mapping\OrderBy;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass=ClientRepository::class)
 */
class Client extends DbObject
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(name="cli_id", type="integer", nullable=false)
     */
    public ?int $id;

    /**
     * @ORM\Column(name="cli_name", type="string", length=255, nullable=true)
     */
    public $name;

    /**
     * @ORM\Column(name="cli_type", type="string", length=255, nullable=true)
     */
    public $type;

    /**
     * @ORM\Column(name="cli_logo", type="string", length=255, nullable=true)
     */
    public $logo;

    /**
     * @ORM\Column(name="cli_email", type="string", length=255, nullable=true)
     */
    public $email;

    /**
     * @ManyToOne(targetEntity="User", inversedBy="clientInitiatives")
     * @JoinColumn(name="cli_initiator", referencedColumnName="usr_id", nullable=true)
     */
    public ?User $initiator;

    /**
     * @ORM\Column(name="cli_inserted", type="datetime", nullable=true, options={"default": "CURRENT_TIMESTAMP"})
     */
    public DateTime $inserted;

    /**
     * @ManyToOne(targetEntity="Organization", inversedBy="clients")
     * @JoinColumn(name="organization_org_id", referencedColumnName="org_id",nullable=false)
     */
    protected $organization;

    /**
     * @ManyToOne(targetEntity="Organization")
     * @JoinColumn(name="client_org_id", referencedColumnName="org_id",nullable=false)
     */
    protected $clientOrganization;

    /**
     * @ManyToOne(targetEntity="WorkerFirm", inversedBy="clients")
     * @JoinColumn(name="worker_firm_wfi_id", referencedColumnName="wfi_id", nullable=true)
     */
    protected ?WorkerFirm $workerFirm;

    /**
     * @OneToMany(targetEntity="ExternalUser", mappedBy="client", cascade={"persist","remove"}, orphanRemoval=true)
     * @OrderBy({"synthetic" = "DESC", "lastname" = "ASC"})
     * 
     * @var ArrayCollection|ExternalUser[]
     */
    public $externalUsers;

    /**
     * Client constructor.
     * @param $id
     * @param $name
     * @param $type
     * @param $logo
     * @param $email
     * @param $organization
     * @param $clientOrganization
     * @param $workerFirm
     * @param $externalUsers
     */
    public function __construct(
      ?int $id = null,
        $initiator = null,
        $type = 'F',
        $name = null,
        $logo = null,
        $email = null,
        $workerFirm = null,
        $externalUsers = null)
    {
        parent::__construct($id, null, new DateTime());
        $this->name = $name;
        $this->type = $type;
        $this->logo = $logo;
        $this->email = $email;
        $this->workerFirm = $workerFirm;
        $this->externalUsers = $externalUsers?:new ArrayCollection();
    }


    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;
        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;
        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(string $logo): self
    {
        $this->logo = $logo;
        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;
        return $this;
    }

    public function setInserted(?DateTimeInterface $inserted): self
    {
        $this->inserted = $inserted;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getOrganization()
    {
        return $this->organization;
    }

    /**
     * @param mixed $organization
     */
    public function setOrganization(Organization $organization): self
    {
        $this->organization = $organization;
        return $this;
    }

    /**
     * @return Organization
     */
    public function getClientOrganization(): ?Organization
    {
        return $this->clientOrganization;
    }

    /**
     * @param Organization $clientOrganization
     */
    public function setClientOrganization(Organization $clientOrganization): self
    {
        $this->clientOrganization = $clientOrganization;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getWorkerFirm(): ?WorkerFirm
    {
        return $this->workerFirm;
    }

    /**
     * @param mixed $workerFirm
     */
    public function setWorkerFirm(?WorkerFirm $workerFirm): self
    {
        $this->workerFirm = $workerFirm;
        return $this;
    }

    /**
     * @return ArrayCollection|ExternalUser[]
     */
    public function getExternalUsers()
    {
        return $this->externalUsers;
    }

    public function addExternalUser(ExternalUser $externalUser): Client
    {
        $this->externalUsers->add($externalUser);
        $externalUser->setClient($this);
        return $this;
    }

    public function removeExternalUser(ExternalUser $externalUser): Client
    {
        $this->externalUsers->removeElement($externalUser);
        return $this;
    }

    /**
     * @return ArrayCollection|ExternalUser[]
     */
    public function getAliveExternalUsers(): ArrayCollection
    {
        return $this->getExternalUsers()->filter(fn(ExternalUser $eu) => !$eu->getDeleted() && !($eu->isSynthetic() && $eu->getUser()->getFirstname() == 'ZZ'));
    }

    public function addAliveExternalUser(ExternalUser $externalUser): Client
    {
        $this->externalUsers->add($externalUser);
        $externalUser->setClient($this);
        return $this;
    }

    public function removeAliveExternalUser(ExternalUser $externalUser): Client
    {
        $this->externalUsers->removeElement($externalUser);
        return $this;
    }

    public function isVirtual()
    {
        if (!$this->externalUsers){
            return true;
        } else {
            $usersHavingEmailAddresses = $this->externalUsers->filter(function(ExternalUser $eu){
                return $eu->getEmail() != null;
            });
            if($usersHavingEmailAddresses->count() == 0){
                return true;
            } else {
                return !$usersHavingEmailAddresses->exists(function(int $i, ExternalUser $eu){
                    return $eu->isOwner();
                });
            }
        }
    }
}

templates/components/activity_client__item.html.twig
<a class="badge-container activity-client-name tooltipped" data-tooltip="">
    <img class="account-logo" src="" alt="">
</a>

templates/components/activity_no_int_act_overlay.html.twig
<div class="no-int-act-overlay {{isMobileView ? 'mr'}} flex-center">
  <div class="no-int-act-bg"></div>
  <div class="no-int-act-text {{isMobileView ? 'c-'}}flex-center">
    <div class="closest-bwd-act"> 
      {#<div class="bwd-act-text">#}
        <i class="fa fa-caret-left"></i>
        <div class="bwd-act-title" data-none="{{'activity_elements.no_int_act.no_backward_activity'|trans}}" data-default="{{'activity_elements.no_int_act.closest_activity'|trans}}"></div>
        <div class="bwd-act-data"></div>
      {#</div>#}
    </div>
    <div class="no-int-act-title-zone">
      <h4 class="c-flex-center">
        <i class="fa fa-chalkboard"></i>
        <span>{{'activity_elements.no_int_act.main_msg'|trans}}</span>
      </h4>
    </div>
    <div class="closest-fwd-act">
      {#<div class="fwd-act-text">#}
        <i class="fa fa-caret-right"></i>
        <div class="fwd-act-title" data-none="{{'activity_elements.no_int_act.no_forward_activity'|trans}}" data-default="{{'activity_elements.no_int_act.closest_activity'|trans}}"></div>
        <div class="fwd-act-data"></div>
      {#</div>#}
    </div>
  </div>
</div>

templates/components/activity_page__participant_item.html.twig
{% macro badge(letter,participation) %}
  {% set currentuser = global.currentuser %}
  {% set colors = { A: 'lightseagreen', T: 'purple', P: 'orange', 'E': 'darkcyan' } %}
  {% set tooltipMsg = { 
      L: 'participants.leader', 
      A: 'tooltip.activity.active_participant_msg', 
      T: 'tooltip.activity.tp_participant_msg', 
      P: 'tooltip.activity.passive_participant_msg', 
      E: 'tooltip.activity.external_user_msg',
      V: 'tooltip.activity.validated_grades',
  } %}

    {% if participation %}
    
        {% if letter == 'L' %}
              <div class="badge-container black-text badge-participation-{{ letter|lower }}" {% if not participation.isLeader %}style="display: none"{% endif %}>
                <i class="fa fa-star tooltipped" data-position="top" data-tooltip="{{ tooltipMsg[letter]|trans }}"></i>
              </div>
        {% elseif letter != 'V' %}
            {% if letter == 'A' and participation.type == 1 or
                  letter == 'T' and participation.type == 0 or 
                  letter == 'P' and participation.type == -1 or 
                  letter == 'E' and participation.user.organization != currentuser.organization
            %}
              <div class="badge-container badge-participation-{{ letter|lower }} tooltipped" data-position="top" data-tooltip="{{ tooltipMsg[letter]|trans }}">
                <div {{ 'style' }}="background: {{ colors[letter] }}">
                  {{ letter }}
                </div>
              </div>
            {% else %}
              <div class="badge-container badge-participation-{{ letter|lower }} tooltipped" data-position="top" data-tooltip="{{ tooltipMsg[letter]|trans }}" style="display: none;">
                <div {{ 'style' }}="background: {{ colors[letter] }}">
                  {{ letter }}
                </div>
              </div>
            {% endif %}
        {% else %}
            {% if participation.status == 3 %}
                <div class="badge-container badge-participation-validated green-text tooltipped" data-position="top" data-tooltip="{{ tooltipMsg[letter]|trans }}">
                  <i class="material-icons">check_circle</i>
                </div>
            {% endif %}
        {% endif %}
    
    {% else %}
        {% if letter == 'L' %}
        <div class="badge-container black-text badge-participation-{{ letter|lower }}" style="display: none;">
          <i class="fa fa-star tooltipped" data-position="top" data-tooltip="{% trans %}participants.leader{% endtrans %}"></i>
        </div>
        {% elseif letter != 'V' %}
          <div class="badge-container badge-participation-{{ letter|lower }} tooltipped" data-position="top" data-tooltip="{{ tooltipMsg[letter]|trans }}" style="display: none;">
            <div {{ 'style' }}="background: {{ colors[letter] }}">
              {{ letter }}
            </div>
          </div>
        {% endif %}

    {% endif %}

{% endmacro %}

{% macro badges(ptype) %}
  <div class="badges">
      {{ _self.badge('L',ptype) }}
      {{ _self.badge('A',ptype) }}
      {{ _self.badge('T',ptype) }}
      {{ _self.badge('P',ptype) }}
      {{ _self.badge('E',ptype) }}
      {{ _self.badge('V',ptype) }}
  </div>
{% endmacro %}


{% set participation_types = { '-1': 'p', '0': 't', '1': 'a' } %}

{% set participation = participant.vars.data %}
{% set participation_type = participation ? participation.type : null %}
{% if entity == 'user' %}
  {% set element = participant.user.vars.data %}
{% else %}
  {% set element = participant.team.vars.data %}
{% endif %}

{% if element %}
    {% if entity == 'user' %}
      {% set elmtName = element.firstname == 'ZZ' ? element.organization.commname : element.fullname %}
    {% else %}
      {% set elmtName = element.name %}
    {% endif %}
{% else %}
    {% set elmtName = '__elmt.name__' %}
{% endif %}

{% set participation_type_class = participation_type
  ? 'participation-type-' ~ participation_types[participation_type]
  : ''
%}



<li
  class="participants-list--item {{ participation_type_class }} {{ not participation ? 'edit-mode new' }}"
  {% if participation %}
    data-id="{{ participation.id }}"
    is-leader="{{ participation.isLeader }}"
    participation-type="{{ participation.type }}"
    mode="{{ mode }}"
  {% endif %}>

  <div class="user-info">
    <img class="user-picture" src="{{ element ? (entity == 'user' ? asset(global.userpicture(element)) : asset(global.teampicture(element))) }}" alt="{{ elmtName }}">
    <span class="elmt-name">{{ elmtName }}</span>
    {{ _self.badges(participation) }}
  </div>

  <div class="user-edit">
    {% if entity == 'user'%}
      <div class="user">
        {{ form_label(participant.user) }}
        {{ form_widget(participant.user, { attr: { class: 'elmt-select' } }) }}
      </div>
    {% else %}
      <div class="team">
        {{ form_label(participant.team) }}
        {{ form_widget(participant.team, { attr: { class: 'elmt-select' } }) }}
      </div>
    {% endif %}
    {% if leadingOption %}
      <div class="leader">
        {{ form_widget(participant.leader) }}
        {{ form_label(participant.leader) }}
        {# <input type="radio" name="{{ participant.leader.vars.full_name }}" id="{{ participant.leader.vars.id }}">
        {{ form_label(participant.leader) }} #}
      </div>
    {% endif %}
    <div class="type">
      {{ form_label(participant.type) }}
      {{ form_widget(participant.type, { attr: { class: 'user-participant-type' } }) }}
    </div>
    <div class="precomment" hidden>
      {{ form_row(participant.precomment) }}
    </div>
  </div>
  <div class="user-actions">
    
    {% if not participation %}
      <a class="btn-flat remove-participant-btn waves-effect waves-light accent-4 btn-flat tooltipped edit" 
      data-position="top"
      data-tooltip="{% trans %}participants.delete{% endtrans %}">
        <i class="fa fa-times"></i>
      </a>
    {% else %}
      <a class="btn-flat waves-effect waves-light accent-4 btn-flat tooltipped edit modal-trigger" href="#deleteParticipant" 
      data-position="top"
      data-tooltip="{% trans %}participants.delete{% endtrans %}">
        <i class="fa fa-times"></i>
      </a>
    {% endif %}
  
    <a class="waves-effect waves-light btn-flat edit-user-btn terminal-btn">
      <span class="material-icons">edit</span>
      <span class="material-icons edit">done</span>
    </a>
  </div>
</li>

templates/components/client__item.html.twig
{% set client = item.vars.data ? item.vars.data : null %}
{% set clientHasUsers = client ? client.aliveExternalUsers|length : 0 %}

    <div class="client {% if item.parent is not null %}collection-item{% endif %}">
    <div class="client-data-zone" {% if not client %}style="display:none"{% endif %}>
        <ul class="flex-center" style="width:100%">
            <li style="margin-right: 20px;position:relative">
                <img class="client-logo-zone" src="{{ client ? asset(global.clientlogo(client)) : asset('lib/img/org/no-picture.png') }}">
            </li>
            <li>

                <div class="client-name c-flex">
                    {% if client and client.name is not empty %}
                    <h5>{{ client.name }}</h5>
                    <small>{{ (clientHasUsers ? (clientHasUsers ~ ' ' ~ 'user'|trans ~ (clientHasUsers > 1 ? 's' : '')) ~ ' - ' : '') ~ ('create_client.partner.' ~ (client.clientOrganization.type == 'F' ? 'firm' : 'independant') ~ '_added_on')|trans ~ ' ' ~ client.inserted|format_datetime('long','none') }}</small>
                    {% endif %}
                </div>
                {#<a href="#deleteClient" class="waves-effect waves-light accent-4 btn-flat modal-trigger" style="margin-left: auto;"><i class="fa fa-times"></i></a>#}
            
                {#
                <div>
                Adresse générique : <span class="client-email"> {{ client.vars.data.email }} </span>
                </div>
                #}
            </li>
            <li class="client-action-btns flex-center" style="visibility:hidden;">

                <div class="btn-flat delete-user-btn tooltipped modal-trigger" href="#deleteClient" data-id="{{clientData.id}}" data-tooltip="{{'delete'|trans}}" data-position="top">
                    <i class="dd-orange-text fa fa-times"></i>
                </div>
                <div>
                    <a class="modify-client-btn btn-flat"><i class="mi create"></i></a>
                </div>
            </li>
        </ul>   
    </div>

    <div class="client-input-zone" {% if client %}style="display:none"{% endif %}>
        <ul class="flex-center-sb">
        {#<h4 style="display:inline-block">{{'create_client.partner.prototype_title'|trans}} __clientNb__</h4>#}
        <div class="client-commname client-elmt" data-prefix-wo="{{ 'create_client.provide_name'|trans }}" data-prefix-w="{{ 'partner'|trans ~ ' : ' }}">
            <a class="btn client-btn client-info-commname dd-orange-text flex-center">
                <img class="selected-client-logo sm-right" src="{{ client ? asset(global.clientlogo(client)) : asset('lib/img/org/no-picture.png')}}" alt="">
                <span class="m-right commname-value">
                    {{ client ? 'partner'|trans ~ ' : ' ~ client.name|trans : 'create_client.provide_name'|trans }}
                </span>
                {#<span class="commname-value">{{ client ? item.vars.data.commname : '' }}</span>#}
            </a>
            <div class="w-firm client-input" style="display:none">
                <div class="input-field">
                    {{ form_label(item.name) }}
                    {{ form_widget(item.name) }}
                </div>
                <select name="firmSelector" style="margin-top:45px"></select>
                {{ form_widget(item.workerFirm) }}
            </div>
        </div>
        <div class="partner-action-buttons">
            <div class="client-type client-elmt" data-prefix-wo="" data-prefix-w="{{'type'|trans ~ ' : '}}">
            <a class="btn client-btn client-info-type white-text flex-center">
                <i class="fa fa-industry m-right"></i>
                <span class="">{{'type'|trans ~ ' : ' ~ 'create_client.type.firm'|trans}}</span>
            </a>
            <div class="client-select-type input-field client-input" style="display: none;">
                {{ form_label(item.type) }}
                {{ form_widget(item.type) }}
            </div>
            </div>
            <a class="validate-client-btn waves-effect waves-light btn tooltip" data-cid="{{client and client.id ? client.id : 0}}"><i class="fa fa-check"></i></a>
            <a href="#deleteClient" class="waves-effect waves-light accent-4 btn-flat modal-trigger" data-cid="{{client and client.id ? client.id : 0}}"><i class="fa fa-trash"></i></a>
        </div>
        {{ form_widget(item.id) }}
        </ul> 
    </div>
    <ul class="individuals collection no-padding" data-prototype="{% apply escape %}{% include 'components/client_external_user__item.html.twig' with { item: item.aliveExternalUsers.vars.prototype, client: item } %}{% endapply %}"
    {#{% if not client or client.aliveExternalUsers|length == 0 %}style="display:none"{% endif %}#}
    >
        
        {% for ikey, individual in item.aliveExternalUsers %}
            {% include "components/client_external_user__item_old.html.twig" with { item: individual, client: item } %}
        {% endfor %}

        {% if not clientHasUsers %}
            <div class="no-user-holder">
                <img src="{{asset('lib/img/legal-person-l.png')}}" alt="legal-person">
                <h5>{{'create_client.partner.no_added_users.title'|trans}}</h5>
                <p>{{'create_client.partner.no_added_users.content'|trans}}</p>
            </div>
        {% endif %}
    
    </ul>
        {#
        <div class="button-field add-user-zone" style="{% if client is null %}display:none ;{% endif %}position: absolute">
            <a class="btn waves-effect waves-light  insert-individual-btn data-cid="{{ client ? client.id : 0 }}"">
                <span>Ajouter utilisateur</span>
            </a>
        </div>
        #}
    </div>

    <div class="fixed-action-btn">
      <a class="btn-floating btn-large add-user-btn tooltipped modal-trigger" href="#addUserClient" data-tooltip="{{'user_list.add_user_btn_tooltip'|trans}}" data-position="top">
        <i class="large mi add"></i>
      </a>
    </div>

templates/components/client_external_user__item_old.html.twig
{% set externalUser = item.vars.data ? item.vars.data : null %}
{% set client = client.vars.data ? client.vars.data : null %}
{% set mailTruncVal = 30 %}
<li class="individual">
    <ul>
        <li class="row element-data collection-item" {% if not externalUser or not externalUser.id or not item.vars.valid %} style="display: none;" {% endif %}>
            <ul class="flex-center-sb">
                <li>
                    <ul class="flex-center">
                    
                        <li class="client-picture-zone">
                            <img class="client-profile-picture" src="{{ externalUser and externalUser.user ? asset(global.userpicture(externalUser.user)) : asset('lib/img/user/no-picture.png') }}">
                        </li>
                    
                        <li>
                            <div class="flex-center">
                                <div style="font-size:17px" class="user-ext-fullname">
                                    {{externalUser ? externalUser.fullname : ''}}
                                </div>
                                <div style="font-size:17px" class="m-left user-ext-email">
                                    {% if externalUser and externalUser.email is not null %}
                                        <i class="fa fa-envelope lime-text text-darken-3 tooltipped" data-tooltip="{{ externalUser.email }}"></i>
                                    {% else %}
                                        <i class="fa fa-envelope tooltipped" data-tooltip="{{ 'create_user.no_provided_email'|trans }}"></i>
                                        <i class="fa fa-minus white-text barred client-user-barred"></i>
                                    {% endif %}
                                </div>
                            </div>
                            <small class="user-ext-position-name">{{externalUser ? (externalUser.positionName ? externalUser.positionName : 'create_client.unknown_position'|trans) : '' }}</small>
            
                        </li>
                    </ul>
                </li>
                <li class="user-action-btns" style="visibility:hidden">
                    {#<a href="#deleteExternalUser" class="waves-effect waves-light accent-4 btn-flat modal-trigger" data-eid="{{ individual.vars.data.id }}" style="margin-left: auto;"><i class="fa fa-times"></i></a>#}
                    <a class="delete-ext-user-btn btn-flat modal-trigger" href="#deleteExternalUser" data-id="{{ externalUser ? externalUser.id : 0 }}">
                        <i class="fa fa-times"></i>
                    </a>
                    <a class="modify-ext-user-btn btn-flat">
                        <i class="material-icons">create</i>
                    </a>
                </li>
            </ul>
        </li>
        <li class="element-input collection-item" {% if externalUser and externalUser.id and item.vars.valid %} style="display: none;" {% endif %}>
            <div class="row flex-center no-margin">
                <div class="col m10 s12">
                    <div class="row">
                        <div class="col m6 s12">
                            <div class="user-fullname user-elmt" data-prefix-wo="" data-prefix-w="{{'create_user.fullname'|trans ~ ' : '}}">
                    
                                <a class="btn user-btn user-info-fullname flex-center" {% if not externalUser or not item.vars.valid %}style="display: none;"{% endif %}>
                                    <span>{{ externalUser ? 'create_user.fullname'|trans ~ ' : ' ~ externalUser.fullname : '' }}</span>
                                </a>
                                <div class="user-select-fullname user-input flex-center" {% if externalUser and item.firstname.vars.valid and item.lastname.vars.valid %}style="display: none;"{% endif %}>
                                    <div class="input-field user-firstname">
                                        {{ form_label(item.firstname) }}
                                        {{ form_widget(item.firstname) }}
                                    </div>
                                    <div class="input-field user-lastname">
                                        {{ form_label(item.lastname) }}
                                        {{ form_widget(item.lastname) }}
                                    </div>
                                </div>
                            </div>
            
                        </div>
                        <div class="col m6 s12">
                            <div class="user-position user-elmt" data-prefix-wo="{{ 'create_user.provide_position'|trans }}" data-prefix-w="{{'create_user.position'|trans ~ ' : '}}">
                                <a class="btn user-btn user-info-position flex-center" {% if not externalUser %} style="display: none;"{% endif %}>
                                    <i class="fa fa-bezier-curve m-right"></i>
                                    <span class="m-right">{{'create_user.provide_position'|trans}}</span>
                                </a>
                                <div class="user-select-position user-input input-field"  {% if externalUser and item.positionName.vars.valid %}style="display: none;"{% endif %}>
                                    {{ form_label(item.positionName) }}
                                    {{ form_widget(item.positionName) }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row no-margin">
                        <div class="col m6 s12">
                            <div class="flex-center-sb">
                                <div class="user-email user-elmt" data-prefix-wo="{{'create_user.provide_email'|trans }}" data-prefix-w="{{'create_user.email_short'|trans ~ ' : '}}">
                    
                                    {% set isTooLong = externalUser and externalUser.email|length > mailTruncVal %}
                                    {% if not isTooLong %}
                                    <a class="btn user-btn user-info-email flex-center">
                                    {% else %}
                                    <a class="btn-flat user-btn user-info-email flex-center tooltipped" data-position="top" data-tooltip="{{externalUser.email}}">
                                    {% endif %}
                                        <i class="fa lime-text text-darken-3 fa-envelope m-right"></i>
                                        <span>{{ externalUser and externalUser.email is not null ? 'create_user.email_short'|trans ~ ' : ' ~ (isTooLong ? externalUser.email|slice(0,mailTruncVal) ~ '...' : externalUser.email) : 'create_user.provide_email'|trans }}</span>
                                    </a>
                                    <div class="user-select-email user-input input-field" style="display:none">
                                        {{ form_label(item.email) }}
                                        {{ form_widget(item.email) }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col m6 s12">
                            <ul class="flex-center-sb">
                                {#}
                                <div class="user-weight user-elmt" data-prefix-wo="{{'create_user.influence'|trans ~ ' : 100'}}" data-prefix-w="{{'create_user.influence'|trans ~ ' : '}}">
                                    <a class="btn user-btn user-info-weight flex-center">
                                        <i class="fa fa-vote-yea m-right"></i>
                                        <span class="m-right">{{'create_user.influence'|trans}} : 100</span>
                                    </a>
                                    <div class="user-select-weight user-input" style="display: none;">
                                        {{ form_label(item.weightValue) }}
                                        {{ form_widget(item.weightValue) }}
                                    </div>
                                </div>
                                #}
                                {#
                                {% if client is null or client.virtual %}
                                    <div class="user-owner user-input">
                                        {{ form_widget(item.owner) }}
                                        {{ form_label(item.owner) }}
                                        <i class="fa fa-question-circle tooltipped" data-position="bottom" data-delay="50" data-tooltip="{% trans %}create_client.owner_tooltip{% endtrans %}"></i>
                                    </div>
                                {% endif %}
                                #}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col s12 m2">
                    <ul class="flex-center">
                        {% if not externalUser or not externalUser.id %}
                            <a class="remove-client-user waves-effect waves-light btn-flat" data-eid="0"><i class="fa fa-trash"></i></a>
                        {% else %}
                            <a class="waves-effect waves-light btn-flat modal-trigger" href="#deleteExternalUser" data-eid="{{ externalUser.id }}"><i class="fa fa-trash"></i></a>
                        {% endif %}
                        
                        <a class="validate-ext-user-btn waves-effect waves-light btn blue darken-2 tooltip" data-cid="{{ client and client.id ? client.id : 0 }}" data-eid="{{ externalUser and externalUser.id ? externalUser.id : 0 }}"><i class="fa fa-check"></i></a>
                    </ul>
                </div>
                {{ form_widget(item.id) }}
            </div>        
        </li>
    </ul>
</li>

templates/components/event_holder__item.html.twig
{% if event is defined %}

  {% include "components/event_element__item.html.twig" with { event: event, em: em, hasTopBorder: false } %}

  {% if embeddedEvents %}
    {% for embeddedEvent in embeddedEvents %}
      {% include "components/event_element__item.html.twig" with { event: embeddedEvent, em: em, hasTopBorder: true } %}
    {% endfor %}
  {% endif %}

{% else %}

  {% include "components/event_element__item.html.twig" %}

{% endif %}